<?php

/**
 * @file
 */

/**
 * Implements hook_theme().
 */
function degov_media_person_theme($existing, $type, $theme, $path) {

  return [
    'media__person' => [
      'template'  => 'media--person',
      'base hook' => 'media',
    ],
    'media__person__author' => [
      'template'  => 'media--person--author',
      'base hook' => 'media',
    ],
    'media__person__embedded' => [
      'template'  => 'media--person--embedded',
      'base hook' => 'media',
    ],
    'media__person__preview' => [
      'template'  => 'media--person--preview',
      'base hook' => 'media',
    ],
    'media__person__search' => [
      'template'  => 'media--person--search',
      'base hook' => 'media',
    ],
    'media__person__usage' => [
      'template'  => 'media--person--usage',
      'base hook' => 'media',
    ],
  ];
}
