<?php

/**
 * @file
 */

use Drupal\views\ViewExecutable;

/**
 * Implements hook_theme().
 */
function degov_node_faq_theme($existing, $type, $theme, $path) {
  return [
    'node__faq' => [
      'template' => 'node--faq',
      'base hook' => 'node',
    ],
  ];
}

/**
 * Implements hook_views_pre_render().
 */
function degov_node_faq_views_pre_render(ViewExecutable $view) {
  if ($view->storage->id() == 'search_faq') {
    $input = $view->getExposedInput();
    $terms = trim(strip_tags($input['volltext']));

    if (!empty($terms)) {
      $terms = array_unique(preg_split('/\s+/', mb_strtolower($terms)));
    }
    else {
      $terms = [];
    }

    $view->element['#attached']['drupalSettings']['degov_node_faq']['search_faq'] = $terms;
    $view->element['#attached']['library'][] = 'degov_node_faq/search_faq';
  }
}
