<?php

/**
 * @file
 */

use Drupal\views\ViewExecutable;

/**
 * Implements hook_theme().
 */
function degov_node_press_theme($existing, $type, $theme, $path) {
  return [
    'node__press' => [
      'template' => 'node--press',
      'base hook' => 'node',
    ],
    'node__press__latest' => [
      'template' => 'node--press--latest',
      'base hook' => 'node',
    ],
    'node__press__long_text' => [
      'template' => 'node--press--long-text',
      'base hook' => 'node',
    ],
    'node__press__preview' => [
      'template' => 'node--press--preview',
      'base hook' => 'node',
    ],
    'node__press__slim' => [
      'template' => 'node--press--slim',
      'base hook' => 'node',
    ],
    'node__press__small_image' => [
      'template' => 'node--press--small-image',
      'base hook' => 'node',
    ],
    'node__press__slideshow' => [
      'template' => 'node--press--slideshow',
      'base hook' => 'node',
    ],
    'node__press__teaser' => [
      'template' => 'node--press--teaser',
      'base hook' => 'node',
    ],
  ];
}

/**
 * Implements hook_views_pre_render().
 */
function degov_node_press_views_pre_render(ViewExecutable $view) {
  if (isset($view) && ($view->storage->id() == 'press_latest_content')) {
    $view->element['#attached']['library'][] = 'degov_node_press/slider';
  }
}
