<?php

/**
 * @file
 */

/**
 * Implements hook_theme().
 */
function degov_media_tweet_theme($existing, $type, $theme, $path) {

  return [
    'media__tweet' => [
      'template' => 'media--tweet',
      'base hook' => 'media',
    ],
    'media__tweet__embedded' => [
      'template' => 'media--tweet--embedded',
      'base hook' => 'media',
    ],
    'media__tweet__preview' => [
      'template' => 'media--tweet--preview',
      'base hook' => 'media',
    ],
    'media__tweet__search' => [
      'template' => 'media--tweet--search',
      'base hook' => 'media',
    ],
    'media__tweet__usage' => [
      'template' => 'media--tweet--usage',
      'base hook' => 'media',
    ],
  ];
}
