name: 'deGov - Social Media Settings'
type: module
description: 'With this module visitors can decide which social media sources they want to see.'
package: deGov
core_version_requirement: ^9
dependencies:
  - 'config_replace:config_replace'
  - 'degov:degov_eu_cookie_compliance'
  - 'degov:degov_media_social_media_embed'
  - 'degov:degov_media_video'
libraries:
  - degov_social_media_settings/process
