<?php

/**
 * @file
 */

/**
 * Implements hook_theme().
 */
function degov_media_contact_theme($existing, $type, $theme, $path) {

  return [
    'media__contact' => [
      'template'  => 'media--contact',
      'base hook' => 'media',
    ],
    'media__contact__embedded' => [
      'template'  => 'media--contact--embedded',
      'base hook' => 'media',
    ],
    'media__contact__preview' => [
      'template'  => 'media--contact--preview',
      'base hook' => 'media',
    ],
    'media__contact__search' => [
      'template'  => 'media--contact--search',
      'base hook' => 'media',
    ],
    'media__contact__usage' => [
      'template'  => 'media--contact--usage',
      'base hook' => 'media',
    ],
  ];
}
