git:
  submodules: false
dist: bionic
language: php
php:
  - '7.3'
services:
  - docker
  - mysql
cache:
  directories:
    - $HOME/.composer/cache
    - /tmp/chromedriver
before_install:
  - mysql -e 'CREATE DATABASE testing;'
install:
  - phpenv config-rm xdebug.ini
  - composer selfupdate --1
  - bash ./scripts/ci/composer--create.sh
  - bash ./scripts/ci/composer--install.sh
  - bash ./scripts/ci/composer--postinstall.sh
  - bash ./scripts/ci/inject_code.sh
jobs:
  include:
    # - stage: "Checks"
    #   name: "Coding standards"
    #   script:
    #     - bash ./scripts/ci/checks--cs.sh
    # - script: bash ./scripts/ci/checks--phpstan.sh
    #   name: "PHPstan"
    # - script: bash ./scripts/ci/checks--npmaudit.sh
    #   name: Npm audit
    # - stage: "Unit Tests"
    #   name: "PHPUnit"
    #   script: bash ./scripts/ci/tests--phpunit.sh
    - stage: "Behat tests"
      name: "Install"
      script:
        - export CI_MYSQL_USERNAME="root"; export CI_MYSQL_PASSWORD=""; bash ./scripts/ci/tests--integration--db-import.sh
        - bash ./scripts/setup_chromedriver.sh
        - bash ./scripts/start_chromedriver.sh
        - bash ./scripts/ci/tests--integration.sh content
