git:
  submodules: false
dist: bionic
language: php
php:
  - '7.3'
services:
  - docker
cache:
  directories:
    - $HOME/.composer
before_script:
  - phpenv config-rm xdebug.ini
  - composer selfupdate --1
jobs:
  include:
    - stage: "Tests"
      name: "Composer setup"
      script:
        - bash ./scripts/ci/composer--create.sh
        - bash ./scripts/ci/composer--install.sh
        - bash ./scripts/ci/composer--postinstall.sh
