git:
  submodules: false
language: php
services:
  - docker
cache:
  directories:
    - $HOME/.composer
before_script:
  - phpenv config-rm xdebug.ini
jobs:
  script:
    - bash ./scripts/ci/composer--create.sh
    - bash ./scripts/ci/composer--install.sh
    - bash ./scripts/ci/composer--postinstall.sh
