<?php

/**
 * @file
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function degov_paragraph_block_reference_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__block_reference' => [
      'template' => 'paragraph--block-reference',
      'base hook' => 'paragraph',
    ],
    'paragraph__block_reference__preview' => [
      'template' => 'paragraph--block-reference--preview',
      'base hook' => 'paragraph',
    ],
    'paragraph__block_reference_sidebar' => [
      'template' => 'paragraph--block-reference-sidebar',
      'base hook' => 'paragraph',
    ],
    'paragraph__block_reference_sidebar__preview' => [
      'template' => 'paragraph--block-reference-sidebar--preview',
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function degov_paragraph_block_reference_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (!empty($form['field_sidebar_right_paragraphs']['widget']) && is_array($form['field_sidebar_right_paragraphs']['widget'])) {
    foreach ($form['field_sidebar_right_paragraphs']['widget'] as $widget_key => &$widget) {
      if (!empty($widget['#paragraph_type']) && $widget['#paragraph_type'] === 'block_reference_sidebar') {
        if (!empty($widget['subform']['field_block_plugin']['widget'][0]['settings']['label'])) {
          $widget['subform']['field_block_plugin']['widget'][0]['settings']['label']['#access'] = FALSE;
        }

        if (!empty($widget['subform']['field_block_plugin']['widget'][0]['settings']['label_display'])) {
          $widget['subform']['field_block_plugin']['widget'][0]['settings']['label_display']['#access'] = FALSE;
          $widget['subform']['field_block_plugin']['widget'][0]['settings']['label_display']['#default_value'] = FALSE;
        }

        if (!empty($widget['subform']['field_block_plugin']['widget'][0]['settings']['views_label_checkbox'])) {
          $widget['subform']['field_block_plugin']['widget'][0]['settings']['views_label_checkbox']['#access'] = FALSE;
        }

        if (!empty($widget['subform']['field_block_plugin']['widget'][0]['settings']['views_label_fieldset'])) {
          $widget['subform']['field_block_plugin']['widget'][0]['settings']['views_label_fieldset']['#access'] = FALSE;
        }
      }
    }
  }
}
