<?php

/**
 * @file
 * Drupal hooks implementations for the degov_paragraph_downloads module.
 */

/**
 * Implements hook_theme().
 */
function degov_paragraph_downloads_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__downloads' => [
      'template' => 'paragraph--downloads',
      'base hook' => 'paragraph',
    ],
    'paragraph__downloads__preview' => [
      'template' => 'paragraph--downloads--preview',
      'base hook' => 'paragraph',
    ],
  ];
}
