<?php

/**
 * @file
 */

/**
 * Implements hook_theme().
 */
function degov_media_citation_theme($existing, $type, $theme, $path) {

  return [
    'media__citation' => [
      'template'  => 'media--citation',
      'base hook' => 'media',
    ],
    'media__citation__embedded' => [
      'template'  => 'media--citation--embedded',
      'base hook' => 'media',
    ],
    'media__citation__full' => [
      'template'  => 'media--citation--full',
      'base hook' => 'media',
    ],
    'media__citation__preview' => [
      'template'  => 'media--citation--preview',
      'base hook' => 'media',
    ],
    'media__citation__search' => [
      'template'  => 'media--citation--search',
      'base hook' => 'media',
    ],
    'media__citation__usage' => [
      'template'  => 'media--citation--usage',
      'base hook' => 'media',
    ],
  ];
}
