version: 2

workflows:
  version: 2
  composer_setup:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: tobiasb/php-cli:7.3-debian
    working_directory: ~/app
    environment:
      BITBUCKET_CLONE_DIR: $CIRCLE_WORKING_DIRECTORY
    steps:
      - checkout
      - run: bash ./scripts/pipeline/composer_setup.sh
