version: 2

workflows:
  version: 2
  composer_setup:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: cimg/php:7.3-node
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer
      - run: bash ./scripts/pipeline/composer_setup.sh
      - save_cache:
          key: composer
          paths:
            - ~/.composer
