<?php

/**
 * @file
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_theme().
 */
function degov_media_video_theme($existing, $type, $theme, $path) {

  return [
    'media__video' => [
      'template' => 'media--video',
      'base hook' => 'media',
    ],
    'media__video__embedded' => [
      'template' => 'media--video--embedded',
      'base hook' => 'media',
    ],
    'media__video__full' => [
      'template' => 'media--video--full',
      'base hook' => 'media',
    ],
    'media__video__preview' => [
      'template' => 'media--video--preview',
      'base hook' => 'media',
    ],
    'media__video__preview_wide' => [
      'template' => 'media--video--preview_wide',
      'base hook' => 'media',
    ],
    'media__video__reference' => [
      'template' => 'media--video--reference',
      'base hook' => 'media',
    ],
    'media__video__search' => [
      'template' => 'media--video--search',
      'base hook' => 'media',
    ],
    'media__video__slider_main_16_9' => [
      'template' => 'media--video--slider-main-16-9',
      'base hook' => 'media',
    ],
    'media__video__usage' => [
      'template' => 'media--video--usage',
      'base hook' => 'media',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function degov_media_video_preprocess_media__video(&$variables) {
  /* @var \Drupal\media\Entity\Media $media */
  $media = $variables['elements']['#media'];

  $variables['video_url'] = $media->toUrl();
  $variables['created'] = $variables['elements']['#media']->created->value;
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function degov_media_video_media_presave(EntityInterface $entity) {
  $bundle = $entity->bundle();
  if ($bundle === 'video' && !$entity->get('field_media_video_embed_field')->isEmpty()) {
    // Check if the field for duration is enabled for the media bundle and that it is empty.
    // There is no need to check the duration again and again if it is already set.
    if ($entity->hasField('field_media_duration') && $entity->get('field_media_duration')->isEmpty()) {
      /** @var \Drupal\degov_common\VideoUtils $videoUtils */
      $videoUtils = \Drupal::service('degov_common.video_utils');
      $duration = $videoUtils->getVideoDuration($entity);
      $entity->set('field_media_duration', [0 => ['value' => $duration]]);
    }
  }
}
