<?php

/**
 * @file
 */

use Drupal\Core\Form\FormState;

/**
 * Implements hook_theme().
 */
function degov_paragraph_webform_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__webform' => [
      'template' => 'paragraph--webform',
      'base hook' => 'paragraph',
    ],
    'paragraph__webform__preview' => [
      'template' => 'paragraph--webform--preview',
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Implements hook_form_alter().
 *
 * @param $form
 * @param \Drupal\Core\Form\FormState $form_state
 * @param $form_id
 */
function degov_paragraph_webform_form_alter(&$form, FormState &$form_state, $form_id) {
  if (strpos($form_id, 'webform_submission_') !== FALSE) {
    $form['actions']['reset'] = [
      '#markup' => '<div class="reset-form">' .
      '<a role="button" tabindex="0"><span class="reset">' . t('Zurücksetzen') . '<i class="fa fa-times" aria-hidden="true"></i></span></a>' .
      '</div>',
      '#weight' => -100,
    ];
  }
}
