name: 'deGov - Sitemap Settings'
type: module
description: 'Enthält algemeine Sitemap Konfiguration.'
package: deGov
core_version_requirement: '^8.8 || ^9'
dependencies:
  - sitemap
  - simple_sitemap
