<?php

/**
 * @file
 */

/**
 * Implements hook_theme().
 */
function degov_node_normal_page_theme($existing, $type, $theme, $path) {
  return [
    'node__normal_page' => [
      'template' => 'node--normal-page',
      'base hook' => 'node',
    ],
    'node__normal_page__full' => [
      'template' => 'node--normal-page--full',
      'base hook' => 'node',
    ],
    'node__normal_page__long_text' => [
      'template' => 'node--normal-page--long-text',
      'base hook' => 'node',
    ],
    'node__normal_page__preview' => [
      'template' => 'node--normal-page--preview',
      'base hook' => 'node',
    ],
    'node__normal_page__slim' => [
      'template' => 'node--normal-page--slim',
      'base hook' => 'node',
    ],
    'node__normal_page__small_image' => [
      'template' => 'node--normal-page--small-image',
      'base hook' => 'node',
    ],
    'node__normal_page__slideshow' => [
      'template' => 'node--normal-page--slideshow',
      'base hook' => 'node',
    ],
    'node__normal_page__teaser' => [
      'template' => 'node--normal-page--teaser',
      'base hook' => 'node',
    ],
  ];
}
