<?php

/**
 * @file
 */

/**
 * Implements hook_theme().
 */
function degov_paragraph_faq_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__faq' => [
      'template' => 'paragraph--faq',
      'base hook' => 'paragraph',
    ],
    'paragraph__faq__preview' => [
      'template' => 'paragraph--faq--preview',
      'base hook' => 'paragraph',
    ],
    'paragraph__faq_list' => [
      'template' => 'paragraph--faq-list',
      'base hook' => 'paragraph',
    ],
    'paragraph__faq_list__preview' => [
      'template' => 'paragraph--faq-list--preview',
      'base hook' => 'paragraph',
    ],
  ];
}

