<?php

/**
 * @file
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function degov_paragraph_overrides_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__media_reference' => [
      'template' => 'paragraph--media-reference',
      'base hook' => 'paragraph',
    ],
    'paragraph__slide' => [
      'template' => 'paragraph--slide',
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Implements hook_modules_installed().
 */
function degov_paragraph_overrides_modules_installed($modules) {
  // Check if we have a config to be installed for the module.
  if (in_array('degov_paragraph_slideshow', $modules)) {
    \Drupal::service('degov_config.module_updater')->onModuleInstalled('degov_paragraph_overrides', 'degov_paragraph_slideshow');
  }
}

/**
 * Implements hook_form_paragraphs_subform_alter().
 */
function degov_paragraph_overrides_form_paragraphs_subform_slideshow_alter(array &$subform, FormStateInterface $form_state, $delta) {
  // Deprecates the type_3 until it is removed from config.
  if (!empty($subform['field_slideshow_type']['widget']['#options']['type_3'])) {
    unset($subform['field_slideshow_type']['widget']['#options']['type_3']);
  }
}
