<?php

/**
 * @file
 */

/**
 * Implements hook_theme().
 */
function degov_paragraph_header_video_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__video_header' => [
      'template' => 'paragraph--video-header',
      'base hook' => 'paragraph',
    ],
    'paragraph__video_header__preview' => [
      'template' => 'paragraph--video-header--preview',
      'base hook' => 'paragraph',
    ],
  ];
}

