<?php

/**
 * @file
 */

/**
 * Implements hook_theme().
 */
function degov_media_instagram_theme($existing, $type, $theme, $path) {

  return [
    'media__instagram' => [
      'template'  => 'media--instagram',
      'base hook' => 'media',
    ],
    'media__instagram__embedded' => [
      'template'  => 'media--instagram--embedded',
      'base hook' => 'media',
    ],
    'media__instagram__preview' => [
      'template'  => 'media--instagram--preview',
      'base hook' => 'media',
    ],
    'media__instagram__search' => [
      'template'  => 'media--instagram--search',
      'base hook' => 'media',
    ],
    'media__instagram__usage' => [
      'template'  => 'media--instagram--usage',
      'base hook' => 'media',
    ],
  ];
}
