config_replace: replace
langcode: en
page_title: 'Sitemap'
message:
  format: 'rich_html'
  value: ''
include_css: true
plugins:
  frontpage:
    enabled: false
    weight: 0
    settings:
      title: 'Front page'
      rss: /rss.xml
  'menu:main':
    enabled: true
    weight: 10
    settings:
      title: 'Main navigation'
      show_disabled: false
