<?php

/**
 * @file
 */

use Drupal\degov_paragraph_slideshow\PreprocessParagraph;

/**
 * Implements hook_theme().
 */
function degov_paragraph_slideshow_theme($existing, $type, $theme, $path) {
  return [
    'node__slideshow' => [
      'template' => 'node--slideshow',
      'base hook' => 'node'
    ],
    'paragraph__slide' => [
      'template' => 'paragraph--slide',
      'base hook' => 'paragraph',
    ],
    'paragraph__slideshow' => [
      'template' => 'paragraph--slideshow',
      'base hook' => 'paragraph',
    ],
  ];
}


/**
 * Implements hook_preprocess_paragraph().
 */
function degov_paragraph_slideshow_preprocess_paragraph(&$variables) {
  /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['paragraph'];
  // Add variables to the slideshow template file.
  if ($paragraph->bundle() == 'slideshow') {
    \Drupal::classResolver(PreprocessParagraph::class)
      ->slider($variables);
  }

  // Add variables to the slideshow template file.
  if ($paragraph->bundle() == 'slide') {
    \Drupal::classResolver(PreprocessParagraph::class)
      ->slide($variables);
  }
}

/**
 * Implements hook_preprocess_video_embed_iframe__youtube().
 */
function degov_paragraph_slideshow_preprocess_video_embed_iframe__youtube(&$variables) {
  $variables['query']['enablejsapi'] = 1;
  $variables['#attached']['library'][] = 'degov_paragraph_slideshow/youtube';
}

/**
 * Implements hook_preprocess_video_embed_iframe__vimeo().
 */
function degov_paragraph_slideshow_preprocess_video_embed_iframe__vimeo(&$variables) {
  $variables['#attached']['library'][] = 'degov_paragraph_slideshow/vimeo';
}
